### ISSUE TITLE
Tracking issue for 3D / 2D Creation

### ISSUE THREAD

**Issue by CoralieGold** [imac2018-3d/StoneEdge#4]
- [X] @Hellowizz, @yoanlcq: Drawing for 3D modeling
- [ ] @datross, @yoanlcq: Modeling / Rigging Guardian
- [ ] @datross, @yoanlcq: Modeling / Rigging Ennemies
- [ ] @datross, @yoanlcq: Modeling / Rigging Dragon
- [ ] @datross, @yoanlcq: Animation Guardian
- [ ] @datross, @yoanlcq: Animation Ennemies
- [ ] @datross, @yoanlcq: Animation Dragon
- [ ] @Hellowizz, @yoanlcq: Texturing
- [X] @CoralieGold: Lore items design
- [x] @Hellowizz, @firegreen, @LanscelThaledric: Level / World design

**Comment by yoanlcq** [comment]
Now THAT's gonna hurt :)

Maybe this should be split into multiple, smaller and more detailed issues (but it's a bit too early. We can do that later). For instance there's gonna be a lot going on with Level / World design.  
Especially high-priority will be to make the "giant low-poly world mesh" that will be loaded at all times and be used as a guide to add detailed chunks in space (as described in the World Streaming part of the Technical Specs).

I have a lot to catch up on, especially the dragon, but I'm still super interested in doing it!

@seaofhymn, I'd like to ask for your status on this. Did you experiment some more with Blender ? Are you still interested in making some 3D models ?
If yes, we'll start giving you specific 3D modeling tasks with hard deadlines. Up until now everything was a bit blurry, but we need to hurry, especially since you'll leave in mid-January. :)

**Comment by firegreen** [comment]
I agree with @yoanlcq, I will put the most of the task in separate issues
And I think we can close this issue

**Comment by yoanlcq** [comment]
@firegreen Let's keep this open until we've properly split it

**Comment by yoanlcq** [comment]
I think I saw the proper way to go for blending animations of different body parts : 
[https://docs.unity3d.com/Manual/AnimationLayers.html](https://docs.unity3d.com/Manual/AnimationLayers.html).  
The main example I can think of is the hero punching while running!

In general the neighbour documentation pages are a very interesting read. I'm sending this because I've been warming up in Blender animation this morning, and tried to understand how Unity deals with animation. Got it working, it's quite motivating!

These documentation pages are especially import to read for us (me, @datross and @Hellowizz (maybe some others) :) )

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
