### ISSUE TITLE
Tracking issue for prototypes

### ISSUE THREAD

**Issue by CoralieGold** [imac2018-3d/StoneEdge#5]
- [x] @luanjunqing: (Unassigned, see items below and my latest comment ^^)
- [x] (Unassigned) Freeze entities (for pause menu and cinematics);
- [x] @CoralieGold: Menus / HUD + Load / Save + Settings / Audio
- [X] @datross: Camera
- [X] @datross, @firegreen: Rails
- [x] @Hellowizz: Physics + move guardian
- [x] @LanscelThaledric: Temporary objects
- [x] @yoanlcq: World queries / Detection / Path finding
- [x] @yoanlcq: World streaming
- [x] @yoanlcq: Input Mapper
- [X] @yoanlcq: FSM
- [x] @firegreen: Smooth transitions
- [X] @datross, @CoralieGold: Animation + Blending

**Comment by yoanlcq** [comment]
I'd like to add two more : "Freeze entities" and "Input Mapper".

### Freeze entities (a.k.a ZA WARUDO (nobody's ever gonna get this reference))  
Required by the pause menu, but also by cinematics. We need to be able to "stop time" for a given set of entities, which means three things:
- Given a GameObject, we need to prevent its Update*() methods;
- Given a GameObject, we need to pause any currently playing animation;
- Given a GameObject, we need to freeze its RigidBody (if any) and restore it when we're done;

Every component in Unity has a `SetActive(bool)` method supposed to do exactly that, but we need proof.  
To find all GameObjects that have a given component, we can use `FindObjectsOfType<MyComponent>()`. This way, we can grab all enemies, then call `SetActive(false)` on their RigidBody, animator, etc.  
The prototype's purpose would be to **prove** that this actually works because I'm not 100% sure myself.

### Input Mapper
As @luanjunqing has seen, handling gamepad input properly for all platforms is super hard, because the button numbers change from one OS to another. Because this is way harder than I anticipated, and I own a gamepad myself, I would like to assign myself to it, and give you @luanjunqing something else (and hopefully doable this time) to work on.  
As you can see there are quite a lot of unchecked boxes in the list in the 1st comment, so feel free to pick one and tell us ! If you're not sure, I will gladly decide for you. :)

**Comment by firegreen** [comment]
I split those tasks into others issues 
I assign people but feel free to say that you can't do the task you're assigned. Ask for help from other people by assigning them in the task and adding "need help" label
If you complete a task, ask someone else to check the work, add a "need check" label and assign some people
